### ISSUE TITLE
Redis Java Library

### ISSUE THREAD

**Issue by sachinwalia2k8** [networknt/light-session-4j#1]
I am wondering if you have decided to use Redis Java Library. I've personally used Jedis, Redisson, Lettuce and would recommend you to consider using Redisson simply because of rich data structures. Moreover it supports auto-reconnect, easy for switching between cluster and standalone mode. For every other libraries I've discovered that you end up creating multiple optional classes if you have switch between these modes.

https://github.com/redisson/redisson

**Comment by stevehu** [comment]
@sachinwalia2k8 We are using the library you have recommended and it works out very good. Thanks a lot for your help. If you have time, please review the code and feel free to point out issues and improve it.

**Comment by sachinwalia2k8** [comment]
Thanks @stevehu I noticed that and that's why I closed the ticket. Will certainly review the code today and provide comments.
